[startup.ssh_init]
name = "bash"
running_delay = -1

[startup.ssh_init.args]
script = """
chmod 400 -R /etc/ssh/
mkdir -p /run/sshd
[ -d /root/.ssh/ ] || mkdir /root/.ssh
"""

[startup.sshd]
name = "core.system"
after = ["ssh_init"]
protected = true

[startup.sshd.args]
name = "/usr/sbin/sshd"
args = ["-e", "-D"]

[startup.mysql_init]
name = "bash"
running_delay = -1

[startup.mysql_init.args]
script = """
mkdir /var/run/mysqld
chown -R mysql /var/lib/mysql
chown -R mysql /var/log/mysql
chown -R mysql /var/run/mysqld
chown -R mysql /var/mysql/binlog
chown -R mysql /var/run/mysqld
find /var/lib/mysql/ -maxdepth 0 -empty -exec  /usr/sbin/mysqld --initialize-insecure --user=mysql --datadir=/var/lib/mysql/ \\;
"""

[startup.mysql]
name = "core.system"
after = ["mysql_init"]
protected = true

[startup.mysql.args]
name = "mysqld"

[startup.db_create]
name = "bash"
running_delay = -1
after = ["mysql"]

[startup.db_create.args]
script = """
user=$DB_USER
pass=$DB_PASS
if [ ! -d /var/lib/mysql/humhub/ ] ; then
mysql -e 'CREATE DATABASE IF NOT EXISTS humhub CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci'
mysql -e \"GRANT ALL ON humhub.* TO '$user'@'localhost' IDENTIFIED BY '$pass'\"
mysql -e 'FLUSH PRIVILEGES'
fi
mysqladmin --user=root --password=  password \"$ROOT_DB_PASS\" &&  password reset successfully || echo ignore error 
"""
[startup.apache]
name = "core.system"
protected = true
after = ["setup"]

[startup.apache.args]
name = "apachectl"
args = [
    "-DFOREGROUND"
]

[startup.cron1]
name = "bash"
recurring_period = 60

[startup.cron1.args]
script = """
/usr/bin/php /var/www/html/humhub/protected/yii queue/run >/dev/null 2>&1
"""

[startup.cron2]
name = "bash"
recurring_period=60

[startup.cron2.args]
script = """
/usr/bin/php /var/www/html/humhub/protected/yii cron/run >/dev/null 2>&1
/usr/bin/php /var/www/html/humhub/protected/yii search/rebuild >/dev/null 2>&1
"""

[startup.cron3]
name = "bash"
recurring_period=7200
after = ["setup"]

[startup.cron3.args]
script = """
backup_time=`date +%Y-%m-%d_%H%M`
humhub_dir='/var/www/html/humhub'
cd $humhub_dir 
mysqldump -uroot -p$ROOT_DB_PASS humhub > dbbackup_$backup_time.sql
find  $humhub_dir -maxdepth 1 -type f -name 'dbbackup*.gz' -delete
gzip dbbackup_$backup_time.sql
unset HISTFILE
if ! restic snapshots ;then echo restic repo does not initalized yet; restic init ; fi > /dev/null
/usr/bin/restic backup -q $humhub_dir
/usr/bin/restic forget -q --prune --keep-hourly 24 --keep-daily 4
"""

[startup.setup]
name = "bash"
running_delay = -1
after = ["db_create"]

[startup.setup.args]
script = """
sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen
export HOME=/root
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

INSTALL_FFP() {
	   cd /var/www/html
           wget https://www.humhub.org/en/download/package/humhub-$HUMHUB_INSTALLATION_VERSION.tar.gz > /dev/null
           tar -xvf humhub-$HUMHUB_INSTALLATION_VERSION.tar.gz --strip-components=1 --directory /var/www/html/humhub > /dev/null
           iyo_file=\"/var/www/html/humhub/protected/humhub/modules/user/authclient/IYO.php\"
           common_file=\"/var/www/html/humhub/protected/config/common.php\"
           dynamic_file=\"/var/www/html/humhub/protected/config/dynamic.php\"

           [ -f \"$iyo_file\" ] || wget https://raw.githubusercontent.com/freeflowpages/freeflow-iyo-module/master/IYO.php -O $iyo_file
           wget https://raw.githubusercontent.com/freeflowpages/freeflow-flist/master/common.php -O $common_file
           wget https://raw.githubusercontent.com/freeflowpages/freeflow-flist/master/dynamic.php -O $dynamic_file

           # for pretty urls
           [ -f /var/www/html/humhub/.htaccess.dist ] && mv /var/www/html/humhub/.htaccess.dist /var/www/html/humhub/.htaccess

           # run migrate script incase humhub version is updated
           /usr/bin/php /var/www/html/humhub/protected/yii migrate/up --includeModuleMigrations=1
           /usr/bin/php /var/www/html/humhub/protected/yii module/update-all
}

if [ -f /var/www/html/humhub/protected/humhub/config/common.php ]; then
        echo humhub version fie exist, checking running version ...
	if [ -z \"$HUMHUB_INSTALLATION_VERSION\" ];then
		echo HUMHUB_INSTALLATION_VERSION was not set,Pease set it in creating FFP container
		exit 1
	fi
        HUMHUB_CURRENT_PRODUCTION_VERSION=$(grep version /var/www/html/humhub/protected/humhub/config/common.php|awk '{print $3}'| tr -d ,| tr -d \')
        if [ $HUMHUB_CURRENT_PRODUCTION_VERSION != $HUMHUB_INSTALLATION_VERSION ];then
		mkdir -p /backup/humhub`date +%Y-%m-%d`
		ls  /var/www/html/humhub
		du -sh  /var/www/html/humhub/*
		cd /var/www/html/humhub
		mv $(ls -A) /backup/humhub`date +%Y-%m-%d`
		INSTALL_FFP
		cp -rp /backup/humhub`date +%Y-%m-%d`/uploads /var/www/html/humhub/uploads
		cp -rp /backup/humhub`date +%Y-%m-%d`/protected/modules /var/www/html/humhub/protected/modules
		cp -rp /backup/humhub`date +%Y-%m-%d`/themes /var/www/html/humhub/themes
		cp -rp /backup/humhub`date +%Y-%m-%d`/protected/config /var/www/html/humhub/protected/config

        else
                echo humhub is already updated and it is version is $HUMHUB_CURRENT_PRODUCTION_VERSION

        fi
else
	echo humhub version file does not exist, checking if it is fresh install ....
	if [ \"$(find /var/www/html/humhub -maxdepth 0 -empty)\" ]; then
		INSTALL_FFP
		# add rest module if not exist
		api_key=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
		if [ ! -d /var/www/html/humhub/protected/modules/rest ];then
			cd /var/www/html/humhub/protected/modules
			git clone https://github.com/freeflowpages/freeflow-rest-api-module.git rest
			chown -R www-data:www-data /var/www/
			chmod -R 775 /var/www/
			/usr/bin/php /var/www/html/humhub/protected/yii module/enable rest
			mysql -uroot -p$ROOT_DB_PASS humhub -e \"insert into api_user (client, api_key, active) values ('client1', '$api_key', 1)\"
		fi
		# add freeflow theme
		if [ ! -d /var/www/html/humhub/themes/Freeflow ];then
			cd /var/www/html/humhub/themes
			git clone https://github.com/freeflowpages/freeflow-theme.git Freeflow
			chown -R www-data:www-data /var/www/; chmod -R 775 /var/www/
			/usr/bin/php /var/www/html/humhub/protected/yii theme/switch Freeflow
		fi
	fi

fi
"""
